language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - hhvm-3.12
  - hhvm-nightly

install:
  - composer install

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm-3.12 || $TRAVIS_PHP_VERSION = hhvm-nightly ]]; then cat hhvm.php.ini >> /etc/hhvm/php.ini; fi

matrix:
  allow_failures:
    - php: hhvm-nightly
