dist: bionic
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

install:
  - composer install

before_script:
  - mysql -u root -e 'create database Phaster;'

script:
  - vendor/bin/phpunit
