language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - hhvm-3.12
  - hhvm-nightly

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
  - composer install

before_script:
  - mysql -u root -e 'create database Phaster;'

script:
  - vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm-3.12
    - php: hhvm-nightly
